### ISSUE TITLE
`crockford::encoding::Write` implementation for String is unsafe

### ISSUE THREAD

**Issue by mTsBucy1** [archer884/crockford#15]
The implementation of `crockford::encoding::Write` for String assumes the passed `u8` is a ASCII byte. However, this is not garanteed, since the trait is public. Therefore calling the trait method with a non ascii `u8` breaks the String invariant without needing unsafe code.
```rust
#[test]
fn unsafe_write() {
    let mut danger = String::new();
    danger.write(0xf0);
    // This panics on my system with the "does not support writing non-UTF-8 byte sequences"
    println!("{}", danger);
}
```

I suggest changing the implementation of the trait to perform an additional bitwise AND with `0x7f`.
This does not incur much additional cost, running the benches does not yield significant regressions.
```rust
impl Write for String {
    fn write(&mut self, u: u8) {
        // The lowest bit gets cleared by the bitwise And.
        unsafe {
            self.as_mut_vec().push(u & 0x7f);
        }
    }
}
```

**Comment by archer884** [comment]
Well, ok, that seems fine.
