### ISSUE TITLE
Incorrect encoding/decoding

### ISSUE THREAD

**Issue by russellbanks** [archer884/crockford#16]
This assertion fails:

```rust
let input = "ZJ75K085CMJ1A";
assert_eq!(input, crockford::encode(crockford::decode(input).unwrap()));
```

```rust
assertion `left == right` failed
  left: "ZJ75K085CMJ1A"
 right: "FJ75K085CMJ1A"

Left:  ZJ75K085CMJ1A
Right: FJ75K085CMJ1A
```

In this case, it appears the first byte encodes/decodes incorrectly.
`ZJ75K085CMJ1A` -> `252 142 89 129 5 101 36 21`
`FJ75K085CMJ1A` -> `124 142 89 129 5 101 36 21`

Both these values also decode to the same u64:

```rust
let correct = crockford::decode("zj75k085cmj1a").unwrap();
let incorrect = crockford::decode("fj75k085cmj1a").unwrap();
assert_ne!(correct, incorrect);
```

```rust
assertion `left != right` failed
  left: 17950419036144289834
 right: 17950419036144289834
```

Decoding `ZJ75K085CMJ1A` with [decode.fr](https://www.dcode.fr/crockford-base-32-encoding) results in a different integer altogether - `18198581554926920725`. This can be verified as correct (using separate websites/services) because re-encoding this (as hexadecimal) using [cryptii](https://cryptii.com/pipes/crockford-base32) returns the original encoding - `ZJ75K085CMJ1A`.

**Comment by archer884** [comment]
Hi! Thanks for your report. As near as I can tell, the correct Crockford-encoded value for `18198581554926920725` is actually `"FS3JSG42PA90N"`. Are you sure these other sites are encoding integers instead of arrays of bytes?

**Comment by archer884** [comment]
For one thing, a Crockford-encoded u64 can't start with z. That'd be bigger than the maximum value of a u64. At least, I'm pretty sure that I have `"FZZZZZZZZZZZZ"` down as the maximum value.

**Comment by archer884** [comment]
I suppose, in that case, it would be a bug to decode any value that long and starting with a z....

**Comment by archer884** [comment]
Ok, try it now. You should get a nice fat error.

**Comment by russellbanks** [comment]
Unless I'm mistaken with this library, it shouldn't be an error. `ZJ75K085CMJ1A` is actually the correct value for my example. My use case is that I'm implementing the Microsoft's [Package Family Name algorithm](https://marcinotorowski.com/2021/12/19/calculating-hash-part-of-msix-package-family-name). Even in the article's author's example, it starts with a `z`.

I have a gist of my code [here](https://gist.github.com/russellbanks/d2ff1f229a635d168be0f71a142b8e7e). Everything after `.take(8)` is just manually encoding with crockford base32.

This is my test case:

```rust
#[cfg(test)]
mod tests {
    use crate::msix_impl::package_family_name::get_package_family_name;

    #[test]
    fn test_package_family_name() {
        assert_eq!(
            get_package_family_name("AppName", "Publisher Software"),
            "AppName_zj75k085cmj1a"
        );
    }
}
```

**Comment by archer884** [comment]
I didn’t say that your value was wrong. I said that the value in question is literally too large to be represented by a u64 integer. If you take a look at the fix I applied, you’ll see that we’re actually overflowing the integer in an attempt to parse it.

So, like I said, this library is for use with 64-bit unsigned identifiers--that is, *integers.* If you want to encode arbitrary bytes, there are other libraries for that. I even link to one in the readme file. :)

**Comment by archer884** [comment]
Ok, think of it this way: Crockford encoding encodes five bits per character, right? So, multiply 13*5 and what do you get? You get 65. Not 64. That means that if you fully load up all 65 bits that COULD be represented by the string "zzzzzzzzzzzzz," you get a number larger than the maximum value that can be represented in only SIXTY-FOUR bits. You get what I'm saying? That's why the max value starts with an F and not a Z. No value beginning with a Z is a valid u64.

**Comment by russellbanks** [comment]
Thanks for explaining :)
